import { strToU8, zipSync } from "fflate";
import * as THREE from "three";
import { GLTFExporter } from "three/addons/exporters/GLTFExporter.js";
import type { WorldData, WorldStats, WorldStyle } from "../types";

export async function exportGlb(group: THREE.Group, name = "worldseed-city.glb"): Promise<void> {
  const binary = await createGlb(group);
  download(new Blob([binary], { type: "model/gltf-binary" }), name);
}

export async function exportStarterKit(
  group: THREE.Group,
  data: WorldData,
  stats: WorldStats,
  style: WorldStyle,
): Promise<void> {
  const binary = await createGlb(group);
  const metadata = JSON.stringify(
    {
      generator: "WorldSeed 0.1.0",
      coordinateSystem: "local meters; X east, Y up, Z south",
      origin: { longitude: data.center[0], latitude: data.center[1] },
      radiusMeters: data.radius,
      style,
      source: data.providerLabel,
      sourceDetails: data.sourceDetails ?? [],
      generatedAt: data.generatedAt,
      stats,
      warnings: data.warnings,
    },
    null,
    2,
  );
  const archive = zipSync(
    {
      "worldseed-city.glb": new Uint8Array(binary),
      "worldseed.json": strToU8(metadata),
      "ATTRIBUTION.md": strToU8(attributionMarkdown(data)),
      "README.md": strToU8(starterReadme()),
      "package.json": strToU8(starterPackage()),
      "index.html": strToU8(starterHtml()),
      "src/main.js": strToU8(starterMain()),
    },
    { level: 6 },
  );
  download(new Blob([archive], { type: "application/zip" }), "worldseed-threejs-kit.zip");
}

function createGlb(group: THREE.Group): Promise<ArrayBuffer> {
  const exporter = new GLTFExporter();
  return exporter.parseAsync(group, {
    binary: true,
    onlyVisible: true,
    trs: false,
  }) as Promise<ArrayBuffer>;
}

function attributionMarkdown(data: WorldData): string {
  const sources = data.attributions.length === 0
    ? "- Synthetic demonstration data generated by WorldSeed."
    : data.attributions
        .map((source) => `- [${source.label}](${source.url}) — [${source.license}](${source.licenseUrl})`)
        .join("\n");
  const sourceDetails = data.sourceDetails && data.sourceDetails.length > 0
    ? `\n\nBuilding geometry sources reported by Overture: ${data.sourceDetails.join(", ")}.`
    : "";
  return `# Data attribution\n\nGenerated by WorldSeed on ${data.generatedAt}.\n\n${sources}${sourceDetails}\n\nPreserve this file when redistributing the generated world. Verify source-specific obligations for your use case.\n`;
}

function starterReadme(): string {
  return `# WorldSeed Three.js Starter\n\nA local-meter Three.js scene exported by WorldSeed.\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nThe model origin is the selected latitude/longitude. X points east, Y points up, and Z points south. See worldseed.json and ATTRIBUTION.md.\n`;
}

function starterPackage(): string {
  return JSON.stringify({
    name: "worldseed-threejs-kit",
    private: true,
    type: "module",
    scripts: { dev: "vite", build: "vite build" },
    dependencies: { three: "^0.179.1" },
    devDependencies: { vite: "^7.1.3" },
  }, null, 2);
}

function starterHtml(): string {
  return `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WorldSeed City</title><style>html,body,#app{height:100%;margin:0}canvas{display:block}</style></head><body><div id="app"></div><script type="module" src="/src/main.js"></script></body></html>`;
}

function starterMain(): string {
  return `import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
const scene = new THREE.Scene(); scene.background = new THREE.Color(0xc9e8ed);
const camera = new THREE.PerspectiveCamera(52, innerWidth / innerHeight, .1, 6000); camera.position.set(300, 220, 300);
const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setSize(innerWidth, innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); document.querySelector("#app").append(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true;
scene.add(new THREE.HemisphereLight(0xffffff, 0x52606d, 2)); const sun = new THREE.DirectionalLight(0xffffff, 2.5); sun.position.set(-200, 400, 180); scene.add(sun);
new GLTFLoader().load("/worldseed-city.glb", ({ scene: city }) => scene.add(city));
addEventListener("resize", () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); });
renderer.setAnimationLoop(() => { controls.update(); renderer.render(scene, camera); });
`;
}

function download(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 2_000);
}
